### ISSUE TITLE
Use API key from geolocation

### ISSUE THREAD

**Issue by devkinetic** [BlueFusionNZ/geocode_lookup#2]
Rather than hardcode the API key, use the existing one. Better yet, we should be implementing the geocoder service plugin already provided by the geolocation module.

```
public function __construct(Client $http_client) {
    $this->guzzleClient = $http_client;
    $this->googleApiKey = \Drupal::config('geolocation.settings')->get('google_map_api_key');
  }
```

**Comment by AndyD328** [comment]
Nice, thanks. If you submit a patch next time you'll get credit on your github account :-)

I'll push up changes later today.
