### ISSUE TITLE
Geocoding multiple Nodes gives all nodes the same lat/long

### ISSUE THREAD

**Issue by devkinetic** [BlueFusionNZ/geocode_lookup#3]
I'm using this module to geocode records being imported with a migration. When done as a batch, the created records all have the same geo data. When I save a node one at a time, everything works. I'm guessing that the service is simply being called rather than creating a new instance for each request.

Because `$this->lat` is already set, the lookup is not performed. I have worked around this by not checking for a value in `$this->lat/long` and perform the lookup each time. It would be better to solve this issue rather than bashing google with many requests for the same thing.

```
public function getLat() {
    $this->performLookup();
    return $this->lat;
}
public function getLong() {
    $this->performLookup();
    return $this->long;
}
```

**Comment by AndyD328** [comment]
Hmm, I've not used it for that.

What if you create a New lookup service in the presave, or add a flag to force a new lookup eg
$lookup->getLat(TRUE) triggers a new lookup and have it default to false.

Or perhaps store the address the lat & lng refer to in the lookup object and if !== the current address then force a new lookup? that might be the most transparent way to do it for users?

**Comment by AndyD328** [comment]
Came to a different conclusion. When setAddress is called it checks if this is the same as the current address. if not then it clears out the data, if it is then it does nothing.

It's in the latest version, can you confirm if that works for you?

**Comment by devkinetic** [comment]
I'm running a slightly modified version, I will integrate your patch and give it a go with my migration script. Will update issue when complete.

**Comment by devkinetic** [comment]
This can be closed.
